Damage card basic
Muttley/foundryvtt-shadowdark pull request #458
Opened 2023-06-21 19:30 UTC by gatesvp

Very first cut at #277.

The changeset does three basic things:

1. Add an `applyDamage` method to Actors
2. Add hook that triggers whenever a user right-clicks a menu, that hook has logic to verify which options are available and to execute `applyDamage` with the appropriate parameters
3. Carries forward additional roll information for our "attack cards", enough for introspection on the rolls we actually made

None of this is really "automation", but I think number 3 will help someone else execute automation.

Video of the feature in action. All of the related Quench tests are still passing.
https://youtu.be/kmyGdTtIEkQ

2023-06-25 09:07 UTC, bakbakbakbakbak requested changes
I've reviewed the changes, and there are some things to look into / comment about.

2023-06-25 09:07 UTC, bakbakbakbakbak commented on system/src/chat/hooks.mjs
> +function _chatMessageIsBasicRoll (message) {
Is your linting on and properly using the config? This is throwing a warning for me if I look at it in VSCodium at least.

2023-06-25 09:07 UTC, bakbakbakbakbak commented on system/src/documents/ActorSD.mjs
> +	 *  * .05 => half damage (resistance)
This should be `0.5` right?

2023-06-25 09:07 UTC, bakbakbakbakbak commented on system/src/documents/ActorSD.mjs
> +		const newHpValue = Math.clamped(currentHpValue - amountToApply, 0, maxHpValue)
See comment above on linting!

2023-06-28 15:54 UTC, bakbakbakbakbak approved these changes
Looks good!

2023-06-28 15:55 UTC, bakbakbakbakbak commented
@gatesvp : As with the other PR, can you add a commit with updates to the `RELEASE_NOTES.md` and I'll merge this.

2023-06-28 16:01 UTC, gatesvp commented
> @gatesvp : As with the other PR, can you add a commit with updates to the `RELEASE_NOTES.md` and I'll merge this.

This piece is done.

It looks like there's a conflict to resolve in the main `shadowdark.mjs` file. I think you know the other changes, will leave that to you to merge?

2023-06-28 16:12 UTC, merged