Fixes issue #560
Muttley/foundryvtt-shadowdark pull request #562
Opened 2023-10-28 23:18 UTC by PrototypeESBU

Additional fixes for Tours and more general clean up.

2023-10-29 19:54 UTC, Muttley requested changes
Looks good apart from the typo.  :)

2023-10-29 19:54 UTC, Muttley commented on system/src/tours/ShadowdarkTourMonsterImporter.mjs
> +					content: "<p>The compendium tab contains collections that are included in the system. Let's open the marcos compendium.</p>",
typo: "marcos" should be "macros"

2023-10-29 20:23 UTC, PrototypeESBU commented on system/src/tours/ShadowdarkTourMonsterImporter.mjs
> +					content: "<p>The compendium tab contains collections that are included in the system. Let's open the marcos compendium.</p>",
Haha, good catch.

2023-10-31 21:10 UTC, Muttley approved these changes

2023-11-01 11:16 UTC, merged